### PR TITLE
Add AppleandMicrosoft.png meme and updated -pages/index.md

### PR DESCRIPTION
**Pull request by muhesh-kumar**
I have added a meme called "AppleandMicrosoft.png" to /assets/memes and updated _pages/index.md with my name, GitHub profile, and image path.

### CODE REVIEW

**Review by nickneos — CHANGES_REQUESTED** [review]
one meme per submission please

**Comment by muhesh-kumar** [comment]
I have added only one meme "AppleandMicrosoft" and not more than that. Can you please check?

**Comment by nickneos** [comment]
the image you uploaded has two images combined into 1

**Comment by muhesh-kumar** [comment]
Oh okay. I didn't know it was an issue. Anyway thanks for spotting this. I will fix this now

**Comment by muhesh-kumar** [comment]
Hello @nickneos! I have modified the image into a single meme and committed the change.

**Pull request merged**
